spring:
  boot:
    admin:
      client:
        enabled: false

  cloud:
    gateway:
      routes:
        - id: catalogue-service-route
          uri: lb://manager-app
          predicates:
            - Path=/catalogue/**
        - id: feedback-service-route
          uri: lb://customer-app
          predicates:
            - Path=/customer/**

eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.1:8761/eureka/
    register-with-eureka: false
  instance:
    prefer-ip-address: true

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://172.17.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

