spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
            issuer-uri: http://172.17.0.1:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://172.17.0.1:8082/realms/selmag

        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: admin-service
            client-secret: "**********"

            scope:
              - metrics
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: "**********"

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.1:8761/eureka/
  instance:
    prefer-ip-address: true