selmag:
  services:
    catalogue:
      uri: lb://catalogue-service
    feedback:
      uri: lb://feedback-service

spring:
  boot:
    admin:
      client:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.17.0.1:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://172.17.0.1:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: "**********"
            authorization-grant-type: authorization_code
            scope:
              - openid
              - view_catalogue
          metrics:
            provider: keycloak
            client-id: customer-app-metrics-client
            client-secret: "**********"
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
              -
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

  zipkin:
    tracing:
      endpoint: http://172.17.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
